### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by wqfeng** [udacity/JavaBasics-BetaTesting-CN#1]
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82455891290923

视频中把 value 翻译成 *数值* 并不准确，变量并不总是数值，应改为 **值** 。

**Comment by wqfeng** [comment]
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82419590420923

文字部分不通顺：
> 这将使 time 具备的任何值加 5！

可改为：
这会让 time 在原值基础上加 5.

**Comment by wqfeng** [comment]
发现测试在提交错误答案的情况下，弹出对话框中的信息没有翻译，至少上面这个练习如此。

**Comment by wqfeng** [comment]
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82447789100923

1. Long 一般翻译为长整型。
2. 视频中的 single code 和 double code 指的是单引号和双引号。

**Comment by wqfeng** [comment]
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82145567120923

double 是双精度浮点型，而不是双值类型，在多处视频中出现。

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
