### ISSUE TITLE
习题集的介绍页面没有翻译

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#11]
## 课程2: 习题集1：变量和基本数据类型 > 1. 介绍
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/591b34c3-bfe4-41c4-82a5-c2fe16ff6f01/concepts/5e9e7dec-e858-4e45-82bb-50cea6de7614)

## 截图
![2018-02-14 14 09 29](https://user-images.githubusercontent.com/34811711/36186129-180908f4-1191-11e8-9fb3-12f4c75dc04b.png)

## 具体描述
页面内容没有翻译

**Comment by GraceyYY** [comment]
#### 课程4：习题集2：控制流程和条件语句 的介绍页面introduction也没有翻译
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a19db15c-fe7a-4605-b2fb-cd63d17a321d/concepts/ce986a1c-1263-4031-96d2-371ba68e2fca)
#### 截图
![2018-02-14 16 35 25](https://user-images.githubusercontent.com/34811711/36189211-28337bec-11a5-11e8-91dc-898fdf156e44.png)

**Comment by ghost** [comment]
这个我后面会一起来翻译

**Comment by ghost** [comment]
已经翻译了，大家可以再看看。翻译得不好的地方可以提出来。
