### ISSUE TITLE
文本显示问题

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#17]
## 课程5: 函数或方法 > 1. 函数简介1
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a8d888e4-42f4-418a-a056-da9c835f9100/concepts/38f71cca-9f97-4fbd-baee-7c39914b9376)

## 截图
![2018-02-18 11 47 36](https://user-images.githubusercontent.com/34811711/36347069-043894a2-14a2-11e8-86d5-512c73d56194.png)

## 具体描述
图中红线标注处链接没有正确显示，可能需要修改一下

**Comment by ghost** [comment]
修正了 Markdown 语法，为国内用户替换了 B 站链接。

thanks~
