### ISSUE TITLE
翻译语境不统一

### ISSUE THREAD

**Issue by lvecode** [udacity/JavaBasics-BetaTesting-CN#18]
## 课程5：函数或方法（java methods）
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a8d888e4-42f4-418a-a056-da9c835f9100/concepts/c07c5776-69bd-4d08-94e3-9aabd827be16)

## 截图
![习题页截图](https://mmbiz.qpic.cn/mmbiz_png/525IphsagSw9jvOiaYmmVZ6ZJu997JIhpOJrpps20OJdM0r3DIibLjjicll6opWp8o8PCov1x6euic88CV6l6P60Zg/0?wx_fmt=png)
![答案页截图](https://mmbiz.qpic.cn/mmbiz_png/525IphsagSw9jvOiaYmmVZ6ZJu997JIhpcuvyeOGlNrRhtlTxiam2mbRK9d40DxaASnqsx3JdQkxk7sLcIN9Es1g/0?wx_fmt=png)

## 具体描述
视频中的代码，第二个参数是作为用户评论的字符串，习题页的翻译是用户评论的字符串，而在答案页里是翻译为“注释”

**Comment by ghost** [comment]
@sylviasun916 答案视频中，28"那一句应该理解成“用户的评论是 ‘好照片！’ ”。“用户的评论是 ‘great photo!’ ”

**Comment by sylviasun916** [comment]
fixed and thanks.
