### ISSUE TITLE
关键字翻译问题

### ISSUE THREAD

**Issue by lvecode** [udacity/JavaBasics-BetaTesting-CN#19]
## 课程3：控制流和条件语句
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/adacacb0-a412-4307-a56e-b2d0e9703ce2/concepts/82b3cfba-da4c-454c-970f-3cad61ff2bc4)

## 截图
![](https://mmbiz.qpic.cn/mmbiz_png/525IphsagSw9jvOiaYmmVZ6ZJu997JIhpibvN2ic2UCKqXZzPsialYTMYLLrBGiaWZqzFhE6aE2g91UBwL3qmpDvzNA/0?wx_fmt=png)
![](https://mmbiz.qpic.cn/mmbiz_png/525IphsagSw9jvOiaYmmVZ6ZJu997JIhpFoic4AwPGFurII6oZVIfkNAOGQS2kbuVBiaH9TInKPEksAKEp3doWsPw/0?wx_fmt=png)

## 具体描述
视频中将break翻译为break条件，在java中break应该是关键字，上图是维基百科关于java关键字的内容。

**Comment by ghost** [comment]
@sylviasun916 仅对于词来说，写作 “break” 或者 “break 关键字” 就好，对于整句话`break;`来说，写作“break 语句”比较好。

**Comment by sylviasun916** [comment]
fixed and thanks.
