### ISSUE TITLE
习题翻译问题

### ISSUE THREAD

**Issue by lvecode** [udacity/JavaBasics-BetaTesting-CN#21]
## 课程6：习题集3：函数或方法
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/5e9b7cc1-6f37-49df-96d4-27bf2e4ce80c/concepts/92f69932-14df-4765-9169-161c48a03963)
## 截图
![](https://mmbiz.qpic.cn/mmbiz_png/525IphsagSyibicgKvRnyZoefmDPvCfQJ7ibuTRIAPBDzu5knjl9iarSWjLEdpElC5XgKXEEq4mxzia9d1iajiamg1k1g/0?wx_fmt=png)

## 具体描述
习题要求的翻译和答案框的注释不一致

**Comment by ghost** [comment]
咦？答案框为什么会有注释？

总之我改掉了。

**Comment by DigitTeaser** [comment]
<img width="1343" alt="2018-02-28 12 01 25" src="https://user-images.githubusercontent.com/19690883/36769420-22f264ce-1c7f-11e8-9fb6-02bc5be66e11.png">

答案仅在完全匹配的情况才判定为正确，建议提示学员“注意多余的空格和行”。
