### ISSUE TITLE
学习时间勾选项

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#22]
## 课程 1：纳米学位介绍 > 5. 练习：抽出时间学习
[课程链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/96df26c0-2b1b-46bc-b621-25a6624df372/modules/566e4396-3738-4f6a-9214-2f30c01ae9b9/lessons/6c078c44-2619-448a-89fd-0e8ca07a0045/concepts/35511891200923)

## 截图
<img width="1705" alt="2018-02-26 17 53 35" src="https://user-images.githubusercontent.com/19690883/36663911-02919554-1b1e-11e8-8a0a-e94d31fb324b.png">

## 具体描述
这节课的中文翻译勾选项没有像上节课（4. 练习：诚信和决心）那样实现？

**Comment by ghost** [comment]
由于这种老的“视频内练习”没有办法翻译，所以下面的文字只是起到一个翻译的作用。

我已经把它替换成了“任务清单”，相当于把视频里的练习做了一个中文的版本在下面。
