### ISSUE TITLE
字幕翻译优化

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#24]
## 课程 1：变量和基本数据类型 > 7. 变量
[课程链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82455891290923)

## 截图
<img width="1652" alt="2018-02-26 18 44 55" src="https://user-images.githubusercontent.com/19690883/36666361-51d4d99e-1b25-11e8-8ad4-20396d2672b8.png">

## 具体描述
00:46 字幕开头的“希望如此”是导师的玩笑话，指希望不会有几分之几的人，可以考虑删去。

**Comment by ghost** [comment]
或者和前面一句话放在一起，或者和后面这一句话分离开。“因为我们不可能有零点几个人，对不对？我希望是的。”

@sylviasun916

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
