### ISSUE TITLE
变量命名的延伸阅读

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#25]
## 课程 1：变量和基本数据类型 > 16. 变量名称
[课程链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82236134510923)

## 截图
<img width="1652" alt="2018-02-26 19 13 49" src="https://user-images.githubusercontent.com/19690883/36667554-36d0a868-1b29-11e8-835a-43c7fa4eaaa1.png">

## 具体描述
建议在教师笔记中给出一些延伸阅读，例如[关于 Variables 的 Java 文档](https://dzone.com/articles/best-practices-variable-and)，[Best Practices for Variable and Method Naming](https://dzone.com/articles/best-practices-variable-and) 等。

**Comment by ghost** [comment]
嗯嗯，加一些辅助资料是很有必要的，我忘记了做这个点。非常感谢花时间寻找资料。

**Comment by ghost** [comment]
添加了以下文字：

> 更多关于命名的最佳实践，可以参考[这篇文章](http://legendmohe.net/2014/04/15/%E8%AF%9115%E6%9D%A1%E5%8F%98%E9%87%8F%E6%96%B9%E6%B3%95%E5%91%BD%E5%90%8D%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/)或者[知乎的讨论](https://www.zhihu.com/question/21440067)。
