### ISSUE TITLE
数据类型大小写

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#26]
## 课程 1：变量和基本数据类型 > 18. 练习：数据类型练习
[课程链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82464489630923)

## 截图
<img width="1652" alt="2018-02-26 19 29 37" src="https://user-images.githubusercontent.com/19690883/36668235-996e2e9e-1b2b-11e8-8f79-04a9c5ea1ed8.png">

## 具体描述
01:13 & 01:18 两处字幕中的 Long 应该改为 long，因为 Java 数据类型大小写敏感。

**Comment by ghost** [comment]
@sylviasun916 这个对于翻译来说好像也没有什么好的系统性解决办法？

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
