### ISSUE TITLE
字幕翻译

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#29]
## 课程5. 函数或方法 > 17. 返回值
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a8d888e4-42f4-418a-a056-da9c835f9100/concepts/246e3e16-3946-4036-a61d-5649cd8e3ec0)

## 截图
![2018-02-26 22 49 14](https://user-images.githubusercontent.com/34811711/36669053-9f23f906-1b47-11e8-904e-b37c66e1e4c0.png)
![2018-02-26 22 56 55](https://user-images.githubusercontent.com/34811711/36669264-624d3cd0-1b48-11e8-972a-f85ac2dcb352.png)

## 具体描述
视频来自Youtube

视频1分22秒处字幕“我们要指定如何改变void”有些难以理解。
这一部分视频在讲返回值的类型可以有很多种，1分22秒英文为“we just have to specify what kind by changing this word void.” 此处如果翻译为“我们只需通过改变void这个单词就可以指定返回值的类型” 会更容易理解一些。

1分24秒处的字幕“利用字符串替换void这个词” 有歧义，String 不翻译会比较好，翻译改为“将void替换为String” 会更容易理解一些。同样，后面讲返回类型int/boolean是不是不翻译会比较好？

**Comment by ghost** [comment]
@sylviasun916 
我觉得要么写全，比如“整数返回类型”要么就直接留“int”这样。

在这里 `String`、`void` 等等它是一个**标识符**，意思是函数的“返回类型为字符串类型”或者“没有返回类型”，而不是“字符串”的名义含义。

最终我是觉得直接保留不翻译比较简洁直观。

**Comment by sylviasun916** [comment]
fixed and thanks.
