### ISSUE TITLE
 视频字幕

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#3]
## Java Foundations > 课程1: 变量和基本数据类型 > 9. 显示输出
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/82496485910923/)

## 截图
![2018-02-07 17 48 56](https://user-images.githubusercontent.com/34811711/35902598-ef96ea14-0c2f-11e8-9afd-a965aeda8dfc.png)

## 具体描述
视频开头第一句话没有中文字幕(Youtube源)
So far, we've programmed the computer to keep track of the number of passengers.

**Comment by ghost** [comment]
墙内版播放器是正常的，YouTube 播放器确实第一句话没有字幕。
@sylviasun916 知道是怎么回事么？

**Comment by sylviasun916** [comment]
已修改，是字幕第一行格式问题。 谢谢反馈！
