### ISSUE TITLE
文档注释格式

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#31]
## 课程5. 函数或方法 > 31. 练习：完成此文档
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a8d888e4-42f4-418a-a056-da9c835f9100/concepts/edec2954-0a67-4b81-bbb0-ed07f2c99301)

## 截图
![2018-02-26 23 57 57](https://user-images.githubusercontent.com/34811711/36672001-d4365fda-1b51-11e8-9728-2a9359b0c1d1.png)

## 具体描述
视频下方，图中标红圈处，文档注释的格式与视频中显示的不一致。

**Comment by ghost** [comment]
这里是说不完整文档的注释，内容是没有错的，但是格式不对。改了下格式以及那句别扭的话：

下面是按照**不完整文档**的 Java 文档生成的 Java 文档注释:
```JAVA
/**
 * 返回整数值的绝对值。如果参数为正，那么就返回
 * 该参数。如果参数为负，则返回该参数的否定形式。
 *
 * @return 返回参数的绝对值。
 */
```
