### ISSUE TITLE
视频数字没有一一对应

### ISSUE THREAD

**Issue by hlm2859506** [udacity/JavaBasics-BetaTesting-CN#33]
## 课程导航+链接
课程7.循环 > 2.练习.数字索引 
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/6e87d8d5-16ff-4aea-8272-808e9ffc5ddf/concepts/aad054b1-4452-4553-978c-216f0cb76a8f

## 截图
![default](https://user-images.githubusercontent.com/36024694/36672489-6c17f164-1b3a-11e8-87ed-cb781226eabe.png)

## 具体描述
视频结尾数组图片数字与问题上的数字，没有对应

**Comment by DigitTeaser** [comment]
## 函数式编程 > 循环 > 数组
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/6e87d8d5-16ff-4aea-8272-808e9ffc5ddf/concepts/65b15c63-8c07-468d-9273-fc1f063e68a8

## 截图
<img width="1652" alt="2018-02-27 16 49 53" src="https://user-images.githubusercontent.com/19690883/36718872-43427940-1bde-11e8-85f1-c35cfb4be6d5.png">

## 具体描述
在上一个小节（19.数组）就出现了这个问题，请知晓。

**Comment by ghost** [comment]
由于我无法改动视频，所以我在视频下方增加了备注：
> 注意： 视频中的 fracNumbers 数组的示意图，第一个数字（ 也就是`fracNumbers[0]` ）应该是 4.0，图示中错误的写成了 0.4。
