### ISSUE TITLE
【翻译问题】【三字棋游戏】 项目介绍

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#34]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/8225f1d6-355d-4ed6-9131-ae76aae6fc57/concepts/18324bf0-02d1-42fb-ad25-192fefb16246

## 截图

<img width="667" alt="2018-02-26 9 30 22" src="https://user-images.githubusercontent.com/9304701/36673130-aa71c2a8-1b3c-11e8-9e4e-44c7c68c4f67.png">

## 具体描述
`字符串 checkGameWinner (char [][] grid) ` 这里的字符串并不用翻译

应为 `String checkGameWinner(char [][]grid) `

**Comment by ghost** [comment]
@sylviasun916 CoCo 内容我已经更正，翻译优化提醒你关注。
`String checkGameWinner(char [][]grid)` 存在于整个单行代码的 MarkDown 标记（\` \`）中，所以很可能不需要翻译。

**Comment by sylviasun916** [comment]
好👌
