### ISSUE TITLE
【翻译添加】【对象的世界】答案：通讯录管理器

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#35]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/008b74dd-d786-4d22-84e6-ace8ae102ba4/concepts/39ae6dfd-342c-40f6-8c16-759566d01c20

## 截图

<img width="1174" alt="2018-02-26 9 38 05" src="https://user-images.githubusercontent.com/9304701/36673463-d8d17dea-1b3d-11e8-9f55-70abeea581da.png">

## 具体描述
我觉得这里答案代码的注释应该翻译一下

**Comment by sylviasun916** [comment]
@ChengGoooo  代码注释之前都是不翻译的，你觉得呢？

**Comment by ghost** [comment]
这个讨论了一下，我的理解是：
1. 对于这种单行的注释，学生有高考的英语水平，或者说在翻译软件的协助下，应该可以阅读。而且这类单行注释，大部分都是些代码里的专有名词，无法翻译，能翻译的只是一些动词之类的，所以阅读难度不算大，翻译的意义也不大。先暂不翻译，根据实际反馈情况来做调整。
2. 大段的注释，例如函数或者方法的说明，可以考虑翻译。
