### ISSUE TITLE
【翻译改善】【用户交互】构建该游戏

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#36]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/297a7f29-2c0d-4e79-863b-d7c83b4026c1/concepts/77077ce9-052b-4886-92ef-9c8696bbc692

## 截图
<img width="1174" alt="2018-02-26 9 48 31" src="https://user-images.githubusercontent.com/9304701/36673765-ceb2881c-1b3e-11e8-9c9a-41321d55f5f2.png">

## 具体描述

00:00s ：`输入扫描器` 旁边可以加个标注 `输入扫描器 (Input Scanner)` 因为前面几课，一直都没有翻译 `Input Scanner`, 这里就突然中文了，有点懵

**Comment by PoBlue** [comment]
<img width="719" alt="2018-02-26 9 53 38" src="https://user-images.githubusercontent.com/9304701/36673953-85be00e0-1b3f-11e8-8b05-70ca69282ad4.png">

# 具体描述

01:29s : `主方法` 旁边可以也加个标注, `主方法（main method）`, 这里指的是 main() 这个方法

**Comment by ghost** [comment]
@sylviasun916 @PoBlue `Input Scanner` 这种 Java 的关键词我觉得不翻译比较好？翻译成`输入扫描器`，会让人觉得很迷的感觉啊。主方法翻译成“main() 方法”好了。

我觉得中文世界已经有很多一看就懵逼的翻译，比如“闭包”这种

**Comment by PoBlue** [comment]
好，老实说，直接来还没有这么懵😂

**Comment by sylviasun916** [comment]
已修改，感谢！
