### ISSUE TITLE
【翻译问题】【猜电影】简介

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#39]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/a36bbd56-725a-469b-a09f-0911a628e05b/concepts/3b5d67c0-4010-44ae-a164-448854171e06

## 截图
<img width="667" alt="2018-02-26 10 03 02" src="https://user-images.githubusercontent.com/9304701/36674439-0d8cbe52-1b41-11e8-869a-ef25ccd05258.png">

## 具体描述
 `因此只会显示电影名称的字母数量。` 感觉应该为 `因此只会显示电影名称字母数量个的 _ `

**Comment by ghost** [comment]
@sylviasun916 翻译问题。已经按照建议修复。
