### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#4]
## Java Foundations > 课程1: 变量和基本数据类型 > 12. 变量(字符串)   
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/48ec5466-55a8-4c2b-b9e8-c95f74afefc8/concepts/81957084470923/)

## 截图
![2018-02-07 18 11 08](https://user-images.githubusercontent.com/34811711/35903571-e6763e5e-0c33-11e8-9999-34fe8ea23889.png)
![-1](https://user-images.githubusercontent.com/34811711/35903576-eb85718a-0c33-11e8-9bc4-675c82ad0d25.jpg)

## 具体描述
视频56s处中文翻译有问题，遗漏了变量名，并且语句不通顺。

英文原文为"We start by typing in the variable type which in this case is a string and then the variable name which is something that we come up with. In this case, I call it driver."

中文翻译可以修改成“我们首先要输入变量类型，在这个案例中是string（字符串），然后输入我们自己想出的变量名，在这里，我把它命名为driver（司机）”

**Comment by ghost** [comment]
@sylviasun916 
> 首先我们要输入变量类型，在这个案例中是 String（字符串），然后输入我们随便想的一个变量名，这里我把它命名为 driver（司机）

把首先放在前面，把 string 改成了 String，其它我觉得 OK。

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
