### ISSUE TITLE
教师笔记图片未正确显示

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#41]
## 函数式编程 > 控制流和条件语句 > 逻辑运算符
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/adacacb0-a412-4307-a56e-b2d0e9703ce2/concepts/7f66ddec-2aa6-41f9-998c-29812c25ab69

## 截图
<img width="1652" alt="2018-02-27 00 00 46" src="https://user-images.githubusercontent.com/19690883/36680638-4c777dc2-1b51-11e8-9a86-93e2445dc416.png">

## 具体描述
教师笔记中的图片没有正确显示，怀疑是 markdown 格式用了全角的 ！符号。

**Comment by ghost** [comment]
@sylviasun916 注意一下这个点。确实是**全角感叹号**引起的，已经修正。
