### ISSUE TITLE
教师笔记链接未正确显示

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#44]
## 函数式编程 > 函数或方法 (Java methods) > 函数简介 1
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a8d888e4-42f4-418a-a056-da9c835f9100/concepts/38f71cca-9f97-4fbd-baee-7c39914b9376

## 截图
<img width="1652" alt="2018-02-27 00 48 00" src="https://user-images.githubusercontent.com/19690883/36683189-e3c25b6a-1b57-11e8-8cb9-c845b949c4c2.png">

## 具体描述
教师笔记中的链接没有正确显示，怀疑是 markdown 格式 [] 与 () 中间多了一个空格。

**Comment by ghost** [comment]
此处已经修复，是用了全角小括号引起的。当时我替换了 YouTube 链接为 Bilibili 疏忽了。

另外这里我补充了一段关于“函数”和“方法”的基本解释。
