### ISSUE TITLE
字幕翻译优化

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#47]
## 函数式编程 > 函数或方法 (Java methods) > 练习：喜欢照片
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/a8d888e4-42f4-418a-a056-da9c835f9100/concepts/c07c5776-69bd-4d08-94e3-9aabd827be16

## 截图
<img width="1652" alt="2018-02-27 13 45 50" src="https://user-images.githubusercontent.com/19690883/36712610-8c9c605c-1bc4-11e8-8889-9e216cc5248e.png">

## 具体描述
00:41 字幕中的 parameters 应译为“形参”，与“实参”对应，完整的句子为：因此形参与实参匹配非常重要。

**Comment by ghost** [comment]
@sylviasun916  parameter 和 argument 同时出现的时候，多半是要区分这俩东西吧。所以这种情形下就应该在翻译的时候有区分了。按照建议的方式改就好。

**Comment by sylviasun916** [comment]
fixed and thanks.
