### ISSUE TITLE
习题集缺少分号

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#49]
## 函数式编程 > 习题集 3：函数或方法 > 练习：问题 4
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/5e9b7cc1-6f37-49df-96d4-27bf2e4ce80c/concepts/886b9d16-9c6f-404f-9bee-dcd68ca81b16

## 截图
<img width="1652" alt="2018-02-27 14 56 41" src="https://user-images.githubusercontent.com/19690883/36714803-9531372e-1bce-11e8-8c3f-bb538fe59bed.png">

## 具体描述
“你的思考”标题下 `return AbsoluteValue` 缺少分号。

**Comment by DigitTeaser** [comment]
## 函数式编程 > 习题集 3：函数或方法 > 练习：问题 5
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/5e9b7cc1-6f37-49df-96d4-27bf2e4ce80c/concepts/ee01cd8f-b768-485b-94df-48c1ebac1129

## 截图
<img width="1652" alt="2018-02-27 14 58 49" src="https://user-images.githubusercontent.com/19690883/36714880-d3d9eb74-1bce-11e8-8cd0-5eb72e569c12.png">

## 具体描述
“你的思考”标题下 `return cost * 0.15` 缺少分号。

**Comment by DigitTeaser** [comment]
## 函数式编程 > 习题集 3：函数或方法 > 练习：问题 7
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/5e9b7cc1-6f37-49df-96d4-27bf2e4ce80c/concepts/97c5dbf3-5abf-4ce4-afd2-e542b41c4d83

## 截图
<img width="1652" alt="2018-02-27 15 01 35" src="https://user-images.githubusercontent.com/19690883/36714993-3442614e-1bcf-11e8-8bec-fcea68bdc3aa.png">

## 具体描述
* “你的思考”标题下 `return c` 以及 `double f = f` 缺少分号。而且代码与正确答案不一样。
* 这个问题的英文描述没有删去。

**Comment by ghost** [comment]
“你的思考” 部分是用户填入的答案，不是课程的内容。

似乎我目前无法创造那类带有交互的练习题，这种不带交互的练习题还无法重置状态，我再思考下有不有更好的解决办法，或者问问美国的同事如何创造带有交互功能的练习题。

最后那个没有删去的英文描述似乎已经在另一个 issue 中解决了。
