### ISSUE TITLE
声明并初始化变量

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#50]
## 函数式编程 > 循环 > while 循环
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/6e87d8d5-16ff-4aea-8272-808e9ffc5ddf/concepts/30ced96a-7684-46ac-b6fa-43337b0b860c

## 截图
<img width="1652" alt="2018-02-27 15 53 15" src="https://user-images.githubusercontent.com/19690883/36716751-5eb43176-1bd6-11e8-92ea-7fa344a91641.png">

## 具体描述
在教师笔记中，建议在 while 循环上面添加 `boolean isRaining = checkWeather();` 声明并初始化变量，使代码更合理。

**Comment by ghost** [comment]
不错的建议，已经修改~
