### ISSUE TITLE
Markdown 格式错误

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#52]
## 函数式编程 > 习题集 4：循环 > 练习：问题 3
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/b5023ff5-752a-4d06-a64e-aceae4651230/concepts/d5352b7b-933a-44c6-83ce-42bc9ae9ca85

## 截图
<img width="1652" alt="2018-02-27 18 00 16" src="https://user-images.githubusercontent.com/19690883/36722639-02092b76-1be9-11e8-8745-1d213685c559.png">

## 具体描述
“输入输出示例”标题下的红框部分 markdown 格式错误，怀疑有多余的 ` 符号。

**Comment by ghost** [comment]
中间多了3个`，已修正。
