### ISSUE TITLE
习题集答案描述未翻译

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#53]
## 函数式编程 > 习题集 4：循环 > 练习：问题 7
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/b5023ff5-752a-4d06-a64e-aceae4651230/concepts/467e5a3f-14e6-4a92-abbf-7fdc4f214689

## 截图
<img width="1652" alt="2018-02-27 18 42 17" src="https://user-images.githubusercontent.com/19690883/36724395-0eaa7e7a-1bee-11e8-894a-c791652161ad.png">

## 具体描述
可参考以下翻译：

外循环会迭代三次：i 分别取值为 1、2、3。在三次循环后，i 会增加至 4 使 `i < rows` 条件不再为真，因此循环结束。每次外循环执行时，一个新的字符串 `thisRow` 都会创建。内循环会在每次迭代时向 `thisRow` 的末尾添加 `#`。对于任意一次外循环迭代，内循环会迭代 i 次：当 i 为 1 时，内循环迭代一次，j 取值为 0。
1. 在外循环第一次迭代结束后，`thisRow` 只是一个 `#`。
2. 外循环第二次迭代时，i 为 2，内循环会迭代两次：j 分别取值为 0、1。由于内循环迭代了两次，向 `thisRow` 添加了两次 `#`，所以当 `thisRow` 在外循环第二次迭代结束后，值为 `##`。
3. 相似地，外循环第三次迭代时，内循环会迭代三次，`thisRow` 会打印为 `###`。

**Comment by ghost** [comment]
我的锅，习题集都是我自己翻译的，这个是漏掉了。

修改改用了你的翻译，谢谢。
