### ISSUE TITLE
习题集翻译问题

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#54]
## 函数式编程 > 习题集 4：循环 > 练习：可选挑战
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/b5023ff5-752a-4d06-a64e-aceae4651230/concepts/c84445e0-9592-43a5-a2f6-bbb8a61b6fe0

## 截图
<img width="1327" alt="2018-02-27 19 57 58" src="https://user-images.githubusercontent.com/19690883/36727551-a29f4b6a-1bf8-11e8-8d6e-639a8fefda8b.png">
<img width="1327" alt="2018-02-27 19 59 18" src="https://user-images.githubusercontent.com/19690883/36727611-ddd98966-1bf8-11e8-8e30-7b84b1d0d92c.png">
<img width="1327" alt="2018-02-27 20 00 38" src="https://user-images.githubusercontent.com/19690883/36727634-f8e715ca-1bf8-11e8-9eb9-ddcf93ffec70.png">

## 具体描述
1. 红框内英文未翻译。
2. 红框内英文未删去。
3. 红框内英文未翻译。

**Comment by ghost** [comment]
已处理。顺便翻译了挑战3 中关于递归的代码注释。
