### ISSUE TITLE
Markdown 格式未正常显示

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#55]
## 函数式编程 > IntelliJ 和调试 > Mac：安装 Java 开发工具包
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/16b4ba3a-1ae6-4ed8-9eb6-0db080ff0b8f/concepts/8ddd79b0-5a61-4e10-883a-95ff366e97a9

## 截图
<img width="1343" alt="2018-02-27 20 11 06" src="https://user-images.githubusercontent.com/19690883/36728079-7f8510fe-1bfa-11e8-949d-408aac17ebbf.png">

## 具体描述
红框内 markdown 链接未正常显示。

**Comment by DigitTeaser** [comment]
## 函数式编程 > IntelliJ 和调试 > Windows：安装 Java 开发工具包
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/16b4ba3a-1ae6-4ed8-9eb6-0db080ff0b8f/concepts/ce0dd8b0-beec-4a62-a5be-53d1017b532a

## 截图
<img width="1343" alt="2018-02-27 20 14 19" src="https://user-images.githubusercontent.com/19690883/36728199-f041f33e-1bfa-11e8-8f1b-87de96aed813.png">
<img width="1343" alt="2018-02-27 20 14 23" src="https://user-images.githubusercontent.com/19690883/36728198-efa6371e-1bfa-11e8-8b46-2cc3787f4d74.png">

## 具体描述
这个小节多处 markdown 格式未正常显示。

**Comment by ghost** [comment]
已修正，并更新 Java10 的信息。
