### ISSUE TITLE
【翻译问题】【太空挑战】简介

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#57]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/22305d04-f4a5-42f1-9a07-beee31fbb29d/concepts/5e96e278-ee04-4701-9e48-d49ce90cff1f

## 截图
<img width="1549" alt="2018-02-27 11 13 26" src="https://user-images.githubusercontent.com/9304701/36736550-e1c98650-1c13-11e8-9454-62b4f5ebed39.png">

## 具体描述
这里的 markdown 格式应该是出现问题了，应该 `这种`

**Comment by ghost** [comment]
已修复
