### ISSUE TITLE
Markdown 格式未正常显示

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#58]
## 函数式编程 > IntelliJ 和调试 > Windows：安装 IntelliJ
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/16b4ba3a-1ae6-4ed8-9eb6-0db080ff0b8f/concepts/a7132a9b-8093-4617-8b40-817647becee3

## 截图
<img width="1343" alt="2018-02-28 03 03 41" src="https://user-images.githubusercontent.com/19690883/36748953-58e12d86-1c34-11e8-9463-da513cc44ff2.png">
<img width="1343" alt="2018-02-28 03 04 17" src="https://user-images.githubusercontent.com/19690883/36748959-5cd42ea2-1c34-11e8-8d5f-461ec596a612.png">

## 具体描述
红框内五处 markdown 格式未正常显示。

**Comment by DigitTeaser** [comment]
## 函数式编程 > IntelliJ 和调试 > IntelliJ 中的 Hello World
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/16b4ba3a-1ae6-4ed8-9eb6-0db080ff0b8f/concepts/1bf68bfd-737d-4c41-96f6-9c086e50926b

## 截图
<img width="1343" alt="2018-02-28 03 14 40" src="https://user-images.githubusercontent.com/19690883/36749494-e61e6f64-1c35-11e8-8793-ef279c29969a.png">
<img width="1343" alt="2018-02-28 03 14 54" src="https://user-images.githubusercontent.com/19690883/36749506-f0d33610-1c35-11e8-80ec-1600f4105092.png">
<img width="1343" alt="2018-02-28 03 15 04" src="https://user-images.githubusercontent.com/19690883/36749529-019e3346-1c36-11e8-9469-38d463c68f88.png">
<img width="1343" alt="36749549-0e3dc13e-1c36-11e8-9b5a-e293806f35cc" src="https://user-images.githubusercontent.com/19690883/36749669-66918c12-1c36-11e8-9ac0-5f81ef2d4b7a.png">
<img width="1343" alt="2018-02-28 03 15 24" src="https://user-images.githubusercontent.com/19690883/36749561-181ea100-1c36-11e8-9e07-2fb494e2229d.png">

## 具体描述
红框内九处 markdown 图片未正常显示。

**Comment by ghost** [comment]
已经讲 MarkDown 语法的图片转换为教室原生的模式，方便国内同学顺畅访问。

**Comment by ghost** [comment]
并且更新了部分教程的内容。
