### ISSUE TITLE
习题集题干内容

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#59]
## 课程6: 习题集3: 函数或方法 > 7.练习：问题7
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/5e9b7cc1-6f37-49df-96d4-27bf2e4ce80c/concepts/97c5dbf3-5abf-4ce4-afd2-e542b41c4d83)

## 截图
![2018-02-28 13 23 27](https://user-images.githubusercontent.com/34811711/36766650-e6dc8742-1c8a-11e8-92a6-ef18b07f3d57.png)

## 具体描述
1.  图中标红圈处标点符号有误，“菜鸟教程” 后面应该是句号而不是顿号。
2. 题干中的英文原文不完整，只有关于第一个函数的信息。建议删除或者补全。

**Comment by ghost** [comment]
已修复。
