### ISSUE TITLE
【翻译问题】【太空挑战】项目提交页面

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#60]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/22305d04-f4a5-42f1-9a07-beee31fbb29d/project

## 截图
<img width="1549" alt="2018-02-28 11 30 22" src="https://user-images.githubusercontent.com/9304701/36768580-e82a720e-1c7a-11e8-8d46-3a25862cfe6c.png">

## 具体描述
应该是太空挑战的项目要求

**Comment by PoBlue** [comment]
<img width="1521" alt="2018-02-28 11 41 05" src="https://user-images.githubusercontent.com/9304701/36768936-622550a0-1c7c-11e8-862c-a3f89a4ba13c.png">

应该翻译为:

 `String` 类型的名称和 `int` 类型的重量

**Comment by PoBlue** [comment]
<img width="1549" alt="2018-02-28 1 53 38" src="https://user-images.githubusercontent.com/9304701/36772118-e9626654-1c8e-11e8-846a-a6ffc4f8b693.png">

`发射成功与否` 应改为 `是否着陆成功`

**Comment by ghost** [comment]
已修改
