### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#62]
## 课程7: 循环 > 21. 新闻发布会（第二部分）
[link](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/6e87d8d5-16ff-4aea-8272-808e9ffc5ddf/concepts/19f816f2-507c-47a9-b067-de20197bb57e)

## 截图
![2018-02-28 15 06 51](https://user-images.githubusercontent.com/34811711/36769617-788260fa-1c99-11e8-9109-87a469fadf12.png)

## 具体描述
视频中的数字为0.423，而字幕中显示为0.433.（视频为Youtube源）

**Comment by sylviasun916** [comment]
fixed and thanks
