### ISSUE TITLE
【页面问题】【选修课程】

### ISSUE THREAD

**Issue by PoBlue** [udacity/JavaBasics-BetaTesting-CN#64]
## 课程导航+链接
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/b53fec6e-c8f1-48cb-a76b-860ea08c7581

## 截图
<img width="1104" alt="2018-02-28 4 26 59" src="https://user-images.githubusercontent.com/9304701/36777388-4a2bbf98-1ca4-11e8-8269-00cb5fc63945.png">

## 具体描述
并不可以进入去。。

**Comment by ghost** [comment]
应该可以访问了，再试试看？
