### ISSUE TITLE
示例代码有误

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#66]
## 课程1:对象的世界 > 14.添加方法
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/008b74dd-d786-4d22-84e6-ace8ae102ba4/concepts/371e2504-39c4-4f6b-902e-c140e45bd763#)

## 截图
![2018-03-01 16 16 50](https://user-images.githubusercontent.com/34811711/36828249-b0a06580-1d6c-11e8-9e45-b51d0e0a49e1.png)
![2018-03-01 16 17 04](https://user-images.githubusercontent.com/34811711/36828251-b21d202e-1d6c-11e8-87c2-fb23a9ad92b8.png)

## 具体描述
在

> 结合所有这一切，ContactsManager 类将如下所示：

下方展示的代码里，searchContact方法里的代码有误，if条件句后面应该是`return myFriends[i]`，而不是图中所示的`return Contact`

**Comment by ghost** [comment]
已修正。
