### ISSUE TITLE
Markdown 链接标题错误

### ISSUE THREAD

**Issue by DigitTeaser** [udacity/JavaBasics-BetaTesting-CN#69]
## 面向对象编程 > 猜电影 > 猜电影
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/a36bbd56-725a-469b-a09f-0911a628e05b/project

## 截图
<img width="1455" alt="2018-03-01 14 29 36" src="https://user-images.githubusercontent.com/19690883/36830103-29dd7fec-1d5d-11e8-91de-a33ef47cbb1a.png">

## 具体描述
审阅标准的 markdown 链接标题写成了“三字旗项目审阅标准”，应该是“猜电影项目审阅标准”。

**Comment by DigitTeaser** [comment]
## 面向对象编程 > 太空挑战 > 太空挑战
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/22305d04-f4a5-42f1-9a07-beee31fbb29d/project

## 截图
<img width="1455" alt="2018-03-01 22 58 10" src="https://user-images.githubusercontent.com/19690883/36851368-060e23d6-1da4-11e8-8a6b-f98c2fa607d5.png">

## 具体描述
审阅标准的 markdown 链接标题写成了“三字旗项目审阅标准”，应该是“太空挑战项目审阅标准”。

**Comment by ghost** [comment]
某个时候突然发现了，已经改啦。
