### ISSUE TITLE
字幕存在问题

### ISSUE THREAD

**Issue by hlm2859506** [udacity/JavaBasics-BetaTesting-CN#7]
## 课程导航+链接
课程3：控制流和条件语句 > 17.逻辑运算符 
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/adacacb0-a412-4307-a56e-b2d0e9703ce2/concepts/7f66ddec-2aa6-41f9-998c-29812c25ab69#

## 截图
![bug1](https://user-images.githubusercontent.com/36024694/35974415-f86ab7d0-0d13-11e8-9c39-d990f103b25c.png)

## 具体描述
视频1分11秒出现字幕问题，原字幕和翻译字幕均存在错误

**Comment by hlm2859506** [comment]
同视频1分32秒也有同样的问题
![bug2](https://user-images.githubusercontent.com/36024694/35974544-798ba66c-0d14-11e8-879b-1d57596416f9.png)

**Comment by hlm2859506** [comment]
3分23秒也存在错误
![bug3](https://user-images.githubusercontent.com/36024694/35974735-3bdeb3b2-0d15-11e8-81f6-0ba31c36883b.png)

**Comment by ghost** [comment]
@sylviasun916 all confirmed:

#### 1'11"
> is 3 less than 5 AND is 2 greater than 15
> ”3 是否小于 5“ 和 ”2 是否小于 3“

#### 1‘32“
> is 3 less than 5 is true
> ”3 小于 5“为真

#### 3'23"
> and this checks if age is less and equal 15 OR age is greater than 60 OR if someone is a student.
> 这个表达式会检查年龄是否小于等于 15 或者大于 60，或者一个人是否是学生

**Comment by sylviasun916** [comment]
已修改，原字幕中有加入 < / > 符合，只是显示不出来，所以全部改为文字 “小于／大于”
