### ISSUE TITLE
示例代码有误

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#70]
## 3.面向对象编程 > 课程2: 用户交互 > 2. input scanner
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/297a7f29-2c0d-4e79-863b-d7c83b4026c1/concepts/55445d3a-d0e1-4ab2-a1e5-9234948e3614)

## 截图
![2018-03-01 20 22 23](https://user-images.githubusercontent.com/34811711/36836866-a9741596-1d8e-11e8-98a7-38d90e21544f.png)

## 具体描述
图中代码中没有变量`sc`，代码应该为`int grade = scanner.nextInt();`

**Comment by ghost** [comment]
已修改。
