### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by GraceyYY** [udacity/JavaBasics-BetaTesting-CN#71]
## 3.面向对象编程 > 课程2: 用户交互 > 11.异常
[LINK](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/916e686d-5a2e-44eb-9acc-796eb0271e35/modules/27171916-1838-4240-88cf-9ad4d98749f3/lessons/297a7f29-2c0d-4e79-863b-d7c83b4026c1/concepts/46b85c84-a9cc-4622-8040-22a5fa8629a9)

## 截图
![2018-03-01 21 06 30](https://user-images.githubusercontent.com/34811711/36838955-b332c432-1d94-11e8-997e-f45c585a5d49.png)

## 具体描述
视频2分22秒处字幕有问题（Youtube源）

**Comment by sylviasun916** [comment]
fixed and thanks!
