### ISSUE TITLE
IntelliJ IDEA配置问题

### ISSUE THREAD

**Issue by lvecode** [udacity/JavaBasics-BetaTesting-CN#73]
## 课程9：IntelliJ和调试——>14.设置项目
[链接](https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/16b4ba3a-1ae6-4ed8-9eb6-0db080ff0b8f/concepts/578b4278-bbef-468b-a731-75262ec50254)

## 截图
![1](https://user-images.githubusercontent.com/14213086/37020764-f3b6e1d4-2157-11e8-8c55-0f13448764ea.png)

## 具体描述
课程中用的是j8版本的JDK，而如果学员安装的是J9的版本，那么在IntelliJ 配置SDK时的目录会有所不同，J9在IntelliJ的正确配置：定位到你JDK安装到的那个路径下，比如我的在：C:\Program Files\Java\jdk1.8.0_73。注意在定位路径的时候定位到JDK的version处即可，不要再往下定位。比如在我的这个路径下面还有bin or lib or jre等等的，这些全部不要。我的定位路径就是：C:\Program Files\Java\jdk1.8.0_73。然后点击：Apply后再点OK

**Comment by ghost** [comment]
对，路径是直接到版本，IDEA 会自动处理剩下的。

另外，
- 修复了 mac 的路径
- 增加了版本的说明，不能直接复制这里的路径，需要根据版本号自行调整
