### ISSUE TITLE
课程的统一性问题

### ISSUE THREAD

**Issue by Einsteinder** [udacity/JavaBasics-BetaTesting-CN#74]

**Comment by Einsteinder** [comment]
有些重复的内容看看是不是删掉比较好：
比如这个在终端运行的问题，在前面介绍ide之前就已经提过了。
![Screenshot 2018-03-10 14.16.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa42f4128b4bc0013daf432/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416743e7854e37a24cbb27ef1122243434d0eee1e020a17b8eb8339a3e73b26dc0d09e5d6680e75933a11acb9d64cea54be23825d99a4fedb1294b7607caddecd5d340c041083fe5837a09e4bc15dff4ce84f51b65e.png)
![Screenshot 2018-03-10 14.14.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa42f4128b4bc0013daf432/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416743e7854e37a24cbb27cf1122b43434d0eee1e020a17b8eb8339a3e73b26dc0d09e5d6680e75933a11acb9d64cea54be23825d99a4fedb1294b7607caddecd5d340c041183fe5837a09e4bc15dff4ce84e5cb65e.png)

还有这个介绍ide的：
前面其实已经很详细的介绍过了，这里可以不用再提了。
![Screenshot 2018-03-10 14.22.05.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa42f4128b4bc0013daf432/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416743e7854e37a24cbb17af1122e43434d0eee1e020a17b8eb8339a3e73b26dc0d09e5d6680e75933a11acb9d64cea54be23825d99a4fedb1294b7607caddecd5d340c041183fe5837a09e4bc15ff24ee9455db65e.png)

**Comment by ghost** [comment]
有道理。暂时先干掉了。
