### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Einsteinder** [udacity/JavaBasics-BetaTesting-CN#75]
棋牌->棋盘

**Comment by Einsteinder** [comment]
![Screenshot 2018-03-10 19.04.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa42f4128b4bc0013daf432/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416743e7854e37a29cbb37cf1132843434d0eee1e020a17b8eb8339a3e73b26dc0d09e5d6680e75933a11acb9d64cea54be23825d99a4fedb1294b7607caddecd5d340c071a83fe5837a09e49ce5ff04ae44d57b65e.png)

**Comment by ghost** [comment]
已修正。
