### ISSUE TITLE
变量名

### ISSUE THREAD

**Issue by Einsteinder** [udacity/JavaBasics-BetaTesting-CN#76]

**Comment by Einsteinder** [comment]
车应该是Rook 而不是Rock
![Screenshot 2018-03-10 20.17.16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa42f4128b4bc0013daf432/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416743e7854e37920cbb27ff1132d43434d0eee1e020a17b8eb8339a3e73b26dc0d09e5d6680e75933a11acb9d64cea54be23825d99a4fedb1294b7607caddecd5d340c041083fe5837a09e48c958ff4ee94453b65e.png)

**Comment by ghost** [comment]
已修正。
