### ISSUE TITLE
缺少分号

### ISSUE THREAD

**Issue by hlm2859506** [udacity/JavaBasics-BetaTesting-CN#8]
## 课程导航+链接
课程4：习题集2：控制流程和条件语句> 8.问题7
{LINK}

## 截图
![1](https://user-images.githubusercontent.com/36024694/35976507-4d9b97fe-0d1b-11e8-9cb0-6281b35885b1.png)

## 具体描述
第一行少了分号

**Comment by ghost** [comment]
thanks~
